export const RESET = "RESET"; //初始化reducer 目前只初始化marketReducer
// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// 页面推送
export const PUSH_PAGE = "PUSH_PAGE";
export const REPLACE_PAGE = "REPLACE_PAGE";

export const NAV_RESET_ROUTE = "NAV_RESET_ROUTE";
export const NAV_RESET_MAIN = "NAV_RESET_MAIN";

// 重置语言
export const RESET_LANGUAGE_REQUEST = "RESET_LANGUAGE_REQUEST";
export const RESET_LANGUAGE_SUCCESS = "RESET_LANGUAGE_SUCCESS";
export const RESET_LANGUAGE_FAILURE = "RESET_LANGUAGE_FAILURE";

// 读取语言
export const SET_LANGUAGE_START = "SET_LANGUAGE_START";
export const SET_LANGUAGE_ENDED = "SET_LANGUAGE_ENDED";

// 读取本地语言
export const READ_LOCAL_LANGUAGE_REQUEST = "READ_LOCAL_LANGUAGE_REQUEST";
export const READ_LOCAL_LANGUAGE_SUCCESS = "READ_LOCAL_LANGUAGE_SUCCESS";
export const READ_LOCAL_LANGUAGE_FAILURE = "READ_LOCAL_LANGUAGE_FAILURE";

// 读取系统语言
export const READ_SYSTEM_LANGUAGE_REQUEST = "READ_SYSTEM_LANGUAGE_REQUEST";
export const READ_SYSTEM_LANGUAGE_SUCCESS = "READ_SYSTEM_LANGUAGE_SUCCESS";
export const READ_SYSTEM_LANGUAGE_FAILURE = "READ_SYSTEM_LANGUAGE_FAILURE";

// 存储语言到本地
export const SAVE_LANGUAGE_LOCAL_REQUEST = "SAVE_LANGUAGE_LOCAL_REQUEST";
export const SAVE_LANGUAGE_LOCAL_SUCCESS = "SAVE_LANGUAGE_LOCAL_SUCCESS";
export const SAVE_LANGUAGE_LOCAL_FAILURE = "SAVE_LANGUAGE_LOCAL_FAILURE";

// 清除本地存储
export const CLEAR_LOCAL_REQUEST = "CLEAR_LOCAL_REQUEST";
export const CLEAR_LOCAL_SUCCESS = "CLEAR_LOCAL_SUCCESS";
export const CLEAR_LOCAL_FAILURE = "CLEAR_LOCAL_FAILURE";

