export const RESET = "RESET"; //初始化reducer 目前只初始化marketReducer
// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// 页面推送
export const PUSH_PAGE = "PUSH_PAGE";
export const REPLACE_PAGE = "REPLACE_PAGE";

export const NAV_RESET_ROUTE = "NAV_RESET_ROUTE";
export const NAV_RESET_MAIN = "NAV_RESET_MAIN";

// 重置语言
export const RESET_LANGUAGE_REQUEST = "RESET_LANGUAGE_REQUEST";
export const RESET_LANGUAGE_SUCCESS = "RESET_LANGUAGE_SUCCESS";
export const RESET_LANGUAGE_FAILURE = "RESET_LANGUAGE_FAILURE";

// 读取语言
export const READ_LANGUAGE_START = "READ_LANGUAGE_START";
export const READ_LANGUAGE_END = "READ_LANGUAGE_END";

// 读取本地语言
export const READ_LOCAL_LANGUAGE_REQUEST = "READ_LOCAL_LANGUAGE_REQUEST";
export const READ_LOCAL_LANGUAGE_SUCCESS = "READ_LOCAL_LANGUAGE_SUCCESS";
export const READ_LOCAL_LANGUAGE_FAILURE = "READ_LOCAL_LANGUAGE_FAILURE";

// 读取系统语言
export const READ_SYSTEM_LANGUAGE_REQUEST = "READ_SYSTEM_LANGUAGE_REQUEST";
export const READ_SYSTEM_LANGUAGE_SUCCESS = "READ_SYSTEM_LANGUAGE_SUCCESS";
export const READ_SYSTEM_LANGUAGE_FAILURE = "READ_SYSTEM_LANGUAGE_FAILURE";


